version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pokemon
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:pokemon@db:5432/pokedex'
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm run migration:run && npm run start"

volumes:
  db-data:
