version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: pokedex


  